[tools]
age = "latest"
argo = "latest"
bat = "latest"
biome = "latest"
cilium-cli = "latest"
clusterctl = "latest"
dotnet = "latest"
eza = "latest"
fastfetch = "latest"
flux2 = "latest"
gh = "latest"
go = "latest"
graalvm = "latest"
gradle = "latest"
helix = "latest"
helm = "latest"
helmfile = "latest"
java = "latest"
jbang = "latest"
jq = "latest"
k0sctl = "latest"
k3d = "latest"
k3sup = "latest"
k9s = "latest"
kind = "latest"
kubectl = "latest"
kubelogin = "latest"
lazygit = "latest"
marksman = "latest"
maven = "latest"
minikube = "latest"
node = "latest"
opencode = "latest"
opentofu = "latest"
quarkus = "latest"
ruff = "latest"
tekton = "latest"
tilt = "latest"
uv = "latest"
zoxide = "latest"
