[tools]
age = "latest"
bat = "latest"
cilium-cli = "latest"
dotnet = "latest"
eza = "latest"
fastfetch = "latest"
gh = "latest"
go = "latest"
graalvm = "latest"
gradle = "latest"
helix = "latest"
helm = "latest"
helmfile = "latest"
java = "latest"
jbang = "latest"
jq = "latest"
k0sctl = "latest"
k9s = "latest"
kubectl = "latest"
kubelogin = "latest"
maven = "latest"
node = "latest"
opentofu = "latest"
quarkus = "latest"
tekton = "latest"
terraform = "latest"
uv = "latest"
zoxide = "latest"
